apiVersion: v1
kind: Service
metadata:
  name: frontend-service-canary
spec:
  type: LoadBalancer
  selector:
    app: myportfolio
    type: frontend
    track: canary
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30009
    targetPort: 4000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment-canary
  labels:
    app: myportfolio
    type: frontend
spec:
  replicas: $CANARY_REPLICAS
  selector:
    matchLabels:
      app: myportfolio
      type: frontend
      track: canary
  template:
    metadata:
      labels:
        app: myportfolio
        type: frontend
        track: canary
    spec:
      containers:
      - name: portfolio
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 4000
        livenessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10