apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment-canary
  labels:
    app: myportfolio
    type: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myportfolio
      type: frontend
      track: canary
  template:
    metadata:
      labels:
        app: myportfolio
        type: frontend
        track: canary
    spec:
      containers:
      - name: portfolio
        image: denyshubh/portfolio
        ports:
        - containerPort: 4000
        livenessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
